### ISSUE TITLE
chown: /znc-data: Operation not permitted

### ISSUE THREAD

**Issue by guidosenff** [znc/znc-docker#1]
When trying to run:
`docker run -it -v znc-data:/znc-data znc:latest --makeconf`

I get the following error:

> chown: /znc-data: Operation not permitted

Which is probably related to the slim image switching to user znc (USER znc) and then running /docker-entrypoint.sh which `chown -R znc:znc "$DATADIR" || exit 1`. znc user isn't allowed to perform the chown.

**Comment by DarthGandalf** [comment]
I wonder why it works for me...

**Comment by guidosenff** [comment]
Me too, I'm trying to see if I can come with solution.

**Comment by DarthGandalf** [comment]
@guidosenff can you try https://github.com/znc/znc-docker/commit/0bc1ba8c28903e5bf651569e7bc71d76f4f22598 before I send it to docker library?

**Comment by mmulich** [comment]
@DarthGandalf The fix worked for me. Thanks!

**Comment by guidosenff** [comment]
Sorry for the late reply, but yes this fixes it! Thanks!

**Comment by tseho** [comment]
@DarthGandalf Thanks for the fix ! Do you know when there will be a new release on docker hub ?

**Comment by DarthGandalf** [comment]
@tseho I think, in a couple of hours after https://github.com/docker-library/official-images/pull/2719 gets merged.
