### ISSUE TITLE
File permissions are set as systemd-timesync:systemd-journal

### ISSUE THREAD

**Issue by mijndert** [znc/znc-docker#10]
I'm trying to run ZNC in Docker on my system using Ubuntu 16.04. 

I'm using my own user 'mijndert':

`uid=1000(mijndert) gid=1000(mijndert) groups=1000(mijndert),27(sudo),33(www-data),117(docker)`

I run this command as my own user:

`docker run -it -v ~/znc-cfg:/znc-data znc --makeconf`

This results in the folder being owned by systemd-timesync:systemd-journal:

```
$ ls znc-cfg
ls: cannot open directory 'znc-cfg': Permission denied
drwx------  5 systemd-timesync systemd-journal 4.0K Apr 25 16:59 znc-cfg
```

What could be the cause of this and can I force the files to be created with my own UID?

**Comment by DarthGandalf** [comment]
Users inside the container don't share UIDs with users outside of the container... That's by design of Docker.

You can try `FROM znc` and change UID of user `znc` to 1000 in your Dockerfile; refer to Alpine docs how to do that.

Also see https://docs.docker.com/engine/security/userns-remap/

**Comment by mijndert** [comment]
I know I can change the UID in a Dockerfile - I just feel like this is a bug in the ZNC Dockerfile you're offering. 

I think the ZNC user is created using a random UID, where (imho) it should be created using a fixed UID.

Please correct me if I'm wrong.

**Comment by DarthGandalf** [comment]
> I know I can change the UID in a Dockerfile - I just feel like this is a bug in the ZNC Dockerfile you're offering.

I think Dockerfile only cares about what happens inside the container. Interaction with host system is on you, and Dockerfile has no control over it. How do you propose to fix this?

> I think the ZNC user is created using a random UID, where (imho) it should be created using a fixed UID.

It can be created with a fixed UID - but which one? 1000 is a common UID for the first user in the system in many distros. But what if someone needs 1001 instead? Also arguably having such common UID would be actually bad, if some random host user would gain access to ZNC files.

And if you're not trying to mix inside and outside - how does exact number matter? Inside container you can refer to the user by name, e.g. with `chown znc foo`

**Comment by mijndert** [comment]
Given all of that, how would your propose supporting volumes while not giving it idiotic permissions to the systemd-timesync user?

**Comment by DarthGandalf** [comment]
Did you read https://docs.docker.com/engine/security/userns-remap/ ?

**Comment by stickybyte** [comment]
To be honest it looks very unprofessional to me cause everyone will run into this issue using your image... 
To have an view on a well done documentation and implementation see at: https://hub.docker.com/r/linuxserver/znc

I switched to this release and it works out of the box

**Comment by DarthGandalf** [comment]
@stickybyte I'm glad linuxserver works for you!

> unprofessional

Note that noone on ZNC team works on ZNC as a daytime job. So the available resources are very limited.

You are free to improve documentation and implementation, of course, and send pull requests - it's all open source.
