### ISSUE TITLE
docker ZNC and Network with custom CA ( hackINT.org)

### ISSUE THREAD

**Issue by rokk4** [znc/znc-docker#11]
How does one import a new rootca.crt into the docker container?
I tried to cp the rootca.crt into /usr/share/ca-certificates  and /etc/ca-certicates and run 

```
/usr/share/ca-certificates # update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
```
but it has no effect and is missing the expectet output about updatet certs.
EDIT: also tried restarting the container

**Comment by DarthGandalf** [comment]
Does https://github.com/gliderlabs/docker-alpine/issues/260 help?

**Comment by rokk4** [comment]
Thank you for your help.
It turned out that I already did the right thing, by copying to /usr/share/ca-certificates and running update-ca-certificates. The .crt-file was not the problem.
Thanks for znc, it's nice software.
