### ISSUE TITLE
No such file (/znc-data/configs/znc.conf)

### ISSUE THREAD

**Issue by cah-adean** [znc/znc-docker#12]
Hi,

Running into a bit of a problem.  Mounting an existing installation I copied over appears to work but the ZNC process appears to be unable to find/process the znc.conf file:

```
/ # /sbin/tini -- su-exec znc:znc /opt/znc/bin/znc --foreground --datadir /znc-data
[WARN  tini (10)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
[ .. ] Checking for list of available modules...
[ .. ] Opening config [/znc-data/configs/znc.conf]...
[ !! ] No such file
[ ** ] Restart ZNC with the --makeconf option if you wish to create this config.
[ ** ] Unrecoverable config error.
/ # ls -l /znc-data/configs/
total 9
-rwxrwxrwx    1 nobody   42949672     10172 Jun 25 14:49 znc.conf
-rwxrwxrwx    1 nobody   42949672      8430 Jun 25 14:49 znc.conf.pre-1.7.x
```

I went so far as to 777 the entire directory thinking it just couldn't see the file.

Here is my launch line:
**docker run -it -p 3000:3000 -v /docker/znc/:/znc-data znc**

Thanks

**Comment by DarthGandalf** [comment]
Show `ls -l / /znc-data`

**Comment by cah-adean** [comment]
I discovered the crux of the problem.  In my infrastructure, chowning the directory from inside the container won't work.  Simply commenting out `chown -R znc:znc "$DATADIR" || exit 1` and building the image fixed my problem.

**Comment by DarthGandalf** [comment]
What is your infrastructure? What does that `chown` command do instead? Does it exit with some error?

**Comment by cah-adean** [comment]
I have an NFS mount to a ZFS share for multiple Docker hosts mounted at /docker, so that I can run any Docker container on any host should I need to move them around for maintenance, additional load balancing, etc.  I have ZFS maintain the ownership of the files as nobody:nogroup.  **/docker/znc** is where I keep my configuration.  

The chown command was changing the ownership of the files on the NFS share to a user that was not able to read the configs (combined with the chmod 0700), but if I left the user as it is.

I know it's not a standard configuration/use case, figured I'd make sure to update the issue with my resolution.

**Comment by DarthGandalf** [comment]
Should now work with docker `--user` parameter with no changes.
