### ISSUE TITLE
Unable to connect to localhost

### ISSUE THREAD

**Issue by jdyyc** [znc/znc-docker#13]
I'm not sure if this is specifically a bug with this container or a larger problem, but I've never run in to this with any other docker containers.
I'm running this container simply as....

`docker run -v $HOME/.znc:/znc-data -p 63333:63333 --name myznc znc`

This works fine for any clients running on other machines.   I can connect from external irc clients and everything is good.

Though, I typically also run irssi on the docker host machine as well and that's where the problem comes in.    The irssi process cannot connect to localhost on 63333.   I can see using lsof that the process is listening on that port, and I can do "telnet localhost 63333" and it makes a connection (though no text ever appears on the connection).

Am I missing something painfully obvious here?

**Comment by DarthGandalf** [comment]
What error message? How exactly you're telling irssi to connect? SSL
enabled?

2018-07-03 4:18 GMT+01:00 jdyyc <notifications@github.com>:

**Comment by jdyyc** [comment]
The connection with irssi simply times out and then it retries.

I'm connecting with 

/connect -SSL localhost 63333

This is what I've always used.

I've tried substituting out localhost for 127.0.0.1, the external ip address, as well as the ip address of the docker container.  None of these have worked.

I've also tried specifying "-h <ip address>" on the command line to specify which IP to connect from.  I've tried all the available IP addresses there with no luck.


My current work around is actually running irssi in another docker container and connecting over to ZNC.  This actually works fine, but I'd still be interested in knowing why the irssi running on docker host can't connect to it.

thanks for your reply!

**Comment by DarthGandalf** [comment]
Try "openssl s_client -connect 127.0.0.1:63333". Also check ZNC logs (when
running with -D) if it sees the connection at all.

2018-07-03 16:58 GMT+01:00 jdyyc <notifications@github.com>:

**Comment by jdyyc** [comment]
openssl s_client -connect 127.0.0.1:63333
CONNECTED(00000003)


And that's it.  No further text for response to input.

Nothing ever shows up in the ZNC logs.

**Comment by DarthGandalf** [comment]
Did you run it with -D?

2018-07-03 17:29 GMT+01:00 jdyyc <notifications@github.com>:

**Comment by jdyyc** [comment]
No.  I have logging turned on (adminlog module), but I wasn't sure how to pass the -D to the ZNC within the container.

**Comment by DarthGandalf** [comment]
docker run -v $HOME/.znc:/znc-data -p 63333:63333 --name myznc znc -D

2018-07-03 18:16 GMT+01:00 jdyyc <notifications@github.com>:

**Comment by jdyyc** [comment]
Ah.  Thanks for your patience.

Ran with Debug and no connection attempts show up on the console when attempting to connect with irssi from the various combinations of source and destination addresses.  Also nothing when attempting to connect with openssl.

(Lots of debug info does show up when connecting from elsewhere)

**Comment by DarthGandalf** [comment]
No idea. Maybe firewall issue?

2018-07-03 18:41 GMT+01:00 jdyyc <notifications@github.com>:

**Comment by jdyyc** [comment]
I kind of gave up on it for now, but you're probably right.  Likely something to do with the iptables configuration of the host machine.  I'll revisit it later.   Thanks for your help!
