### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [znc/znc-docker#14]
Hi,

The Znc docker package is building and running fine at my end for ARM64v8 architecture.

Branch used to build is: 
````
full
````
then build with 
````
slim
````

Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by DarthGandalf** [comment]
Hi, it's in
https://github.com/docker-library/official-images/blob/master/library/znc#L4

2018-07-04 13:12 GMT+01:00 odidev <notifications@github.com>:

**Comment by odidev** [comment]
@DarthGandalf : I have checked this : 
https://github.com/docker-library/official-images/blob/master/library/znc#L4

But this has support for ```amd64, arm32v6```
Can you please add it for ```arm64v8``` too.

I have verified working of ```ZNC``` with arm64v8 architecture.

**Comment by DarthGandalf** [comment]
You can do it :)

2018-07-09 5:30 GMT+01:00 odidev <notifications@github.com>:

**Comment by odidev** [comment]
@DarthGandalf : Thanks :)

PR raised at https://github.com/docker-library/official-images/pull/4560

-Regards

**Comment by lag-linaro** [comment]
@odidev beat me to it. :smile: Any chance you can ping me please? Are you on FreeNode?

**Comment by odidev** [comment]
```ZNC``` is working very well on ```arm64v8``` now.
The image even works via ```docker pull```.

So this ticket can be closed.

Regards,
