### ISSUE TITLE
having minor issues with znc running

### ISSUE THREAD

**Issue by ZachBacon** [znc/znc-docker#15]
the docker image seems to be stuck at 
Staying open for debugging [pid: 201]
ZNC 1.7.0 - https://znc.in

for roughly 10 minutes. 

I'm actually at a loss as the config I had works just fine on a local based setup but when I moved to a docker instance. 
Perhaps I'm missing something that I'm not sure of. I followed the instructions of maintaining my current config, with some minor adjustments for the ssl cert I have with it so the config could find it. But it's like the image is frozen.

**Comment by DarthGandalf** [comment]
What flags you passed to docker?
Did you try to connect to it via TCP from your IRC client or browser?

2018-07-15 23:59 GMT+01:00 Zach Bacon <notifications@github.com>:

**Comment by ZachBacon** [comment]
I just tried, seems to be working, especially in detached mode, however, seems the I can't access the webui once it's loaded.

**Comment by DarthGandalf** [comment]
You didn't answer my question. Also define "can't access"

2018-07-17 11:35 GMT+01:00 Zach Bacon <notifications@github.com>:

**Comment by ZachBacon** [comment]
apologied for taking a while to get back to you, Managed to resolve the issue. It was more my end than anything else. I don't remember the exact fix, due to the fact I'm not currently at my desktop. But it's working

**Comment by zloveless** [comment]
@ZachBacon Do you remember how you resolved this? Getting this on a docker-compose setup.
