### ISSUE TITLE
Docker images have vulnerabilities

### ISSUE THREAD

**Issue by novns** [znc/znc-docker#18]
As [reported](https://hub.docker.com/r/library/znc/tags/) by the docker hub (you need to be logged in) there are major vulnerabilities in `libicu`, `berkeleydb` and `heimdal` components.

I'm not sure whether is it safe to use docker images currently.
Rebuilding them with updated packages would not hurt.

**Comment by DarthGandalf** [comment]
As it's official image, we don't have direct control over when it's rebuilt. However, probably it's time to release new minor version anyway... That would trigger the rebuilt for sure.

Using the existing image is safe as long as you don't use those features: libicu is used for encoding support on client side and server side. Berkeleydb and heimdal - no idea, probably they are dependencies of some dependencies.
