### ISSUE TITLE
Allow usage with --user option

### ISSUE THREAD

**Issue by devster31** [znc/znc-docker#20]
This is a feature request to have this container work with `--user [docker]` and `user: [docker-compose]` options.
The way the current startup sequence is structured requires running `chown` to a container user with a predefinite UID and GID.
Other images, however, (e.g. official postgres [here](https://github.com/docker-library/postgres/blob/45b855af13f6a753fa77bb830c482af6a69d50da/9.5/docker-entrypoint.sh#L51-L54) for example), use lines like `chown -R "$(id -u)" "$PGDATA" 2>/dev/null || :`.
Testing for `$(id -u) = 0` and changing `znc:znc` to `"$(id -u):$(id -g)"`  in:
https://github.com/znc/znc-docker/blob/207358a4830566913c1f9b6c0cdb870c5b6c7bb3/slim/50-chown.sh#L4
as well as tweaking `su-exec` from
https://github.com/znc/znc-docker/blob/207358a4830566913c1f9b6c0cdb870c5b6c7bb3/slim/99-launch.sh#L5
should be sufficient to allow arbitrary `--user` values and not break anything.

**Comment by DarthGandalf** [comment]
Thanks for the advice!
