### ISSUE TITLE
Enabling Cyrusauth, either argument, can't connect using SASL

### ISSUE THREAD

**Issue by FingerlessGlov3s** [znc/znc-docker#21]
I've configured ZNC on my docker host and its working great expect one issue.

When I enable Cyrusauth using either auxprop or saslauthd. I set my client, (My choice is Hexchat) to connect via SASL it don't connect.

Am I missing something or does the docker container not support it?

using znc:latest image

**Comment by DarthGandalf** [comment]
Cyrusauth has nothing to do with SASL in your client. https://github.com/znc/znc/issues/296

**Comment by FingerlessGlov3s** [comment]
I was told on Freenode #znc, that SASL via IRC client to ZNC didn't auth against ZNC users but system users (PAM, etc) when using Cyrusauth.

So to login to ZNC you have to use serverpassword, which will auth you against the ZNC user list.
I wanted to auth against ZNC using SASL but if that's not possible thats fine.

**Comment by DarthGandalf** [comment]
There are 2 things which are unrelated, but share the name SASL.

* Authentication: the method how client tells ZNC who the user is; it can use server password, or SASL on IRC protocol level. Follow znc/znc#296 for this SASL.
* Authorization: the way how ZNC checks which users are valid and which are not. Usually, they are users internal to ZNC, but ZNC has ability to query external services, e.g. via cyrusauth or imapauth. Cyrusauth implements SASL between ZNC and operating system, but it has nothing to do with the way how your Hexchat sends the password to ZNC.

Note that I'm using the terms authentication and authorization slightly wrong here, but this distinguishing is close enough.

What you describe sounds like you want ZNC to have external user list, and cyrusauth *might* help there. But it might be non-trivial to setup; I think you need saslauthd, not auxprop, and you may need to bind the socket path to docker container to make the sasl daemon running on docker host accessible to the client in cyrusauth module. If you have an IMAP server working already, imapauth module may be easier to setup. If you manage cyrusauth to work, the docs how to do that would be appreciated.

**Comment by FingerlessGlov3s** [comment]
Sorry if if my explanation was wrong but I would like to auth against ZNC using SASL

https://github.com/znc/znc/issues/296 is what I'm after. Does that just work out of the box? or do I need to change some settings first? I tried SASL Authentication before missing with Cyrusauth but thought I needed Cyrusauth for it to work. Which is not the case it seems, as its for using an external authentication provider as it were.
