### ISSUE TITLE
Option to run docker znc with different user and group

### ISSUE THREAD

**Issue by nmajin** [znc/znc-docker#24]
Could there be an option to pass in an environment variable for specific UID and GUID? It appears the user and group the container runs under is 100:101, which is causing some issues with permissions when using the persistent volume.

**Comment by DarthGandalf** [comment]
Can you show the exact command you're running? And the error message?

Also any example image which does it via PUID env?

**Comment by nmajin** [comment]
Sure, here is the command, and it immediately dies at that last line:

```
synology:/volume1/docker/znc$ docker run -it --name znc -v `pwd`/data:/znc-data --user $(id -u):$(id -g) znc --makeconf
[ .. ] Checking for list of available modules...
[ ** ] 
[ ** ] -- Global settings --
[ ** ] 
[ ?? ] Listen on port (1025 to 65534): 6698
[ ?? ] Listen using SSL (yes/no) [no]: yes
[ ?? ] Listen using both IPv4 and IPv6 (yes/no) [yes]: 
[ .. ] Verifying the listener...
[ ** ] Unable to locate pem file: [/znc-data/znc.pem], creating it
[ .. ] Writing Pem file [/znc-data/znc.pem]...
```

Here is the container state after:
```
CONTAINER ID        IMAGE                          COMMAND                  CREATED              STATUS                            PORTS                    NAMES
71f58ffb0ecc        znc                            "/entrypoint.sh --ma…"   About a minute ago   Exited (137) About a minute ago                            znc
```

And here is what got created (almost appears to not have proper permissions, and the account I am using on my synology here is an admin) 
```
synology:/volume1/docker/znc$ ll data/
total 0
drwxrwxrwx+ 1 user123 users 28 Jan  5 19:11 .
drwxrwxrwx+ 1 user123 users  8 Jan  5 19:03 ..
drwxrwxrwx+ 1 user123 users  0 Jan  5 19:11 configs
-rwxrwxrwx+ 1 user123 users  0 Jan  5 19:11 znc.pem
```

For another image that is working fine, I was able to use this with specifying the PUID and PGUID environment params and no issue at all: https://hub.docker.com/r/linuxserver/znc

**Comment by KnKay** [comment]
What worked for me... Is mounting the whole folder, not just the config. 
Not sure why!

**Comment by nmajin** [comment]
> What worked for me... Is mounting the whole folder, not just the config. Not sure why!

Yep, that did work...so for the sake of finally getting this working I will close out this issue.
