### ISSUE TITLE
is readme wrong?

### ISSUE THREAD

**Issue by felixsanz** [znc/znc-docker#26]
Readme says:

```
To run ZNC:

$ docker run -p 6697:6697 -v znc-cfg:/znc-data znc

The port should match the port you used during --makeconf. Note that 6667 is often blocked by web browsers, and therefore is not recommended.
```

Why the `docker run` uses port 6697 but then port 6667 is mentioned? which one exposes the container?

**Comment by DarthGandalf** [comment]
No port is exposed by default. During --makeconf you need to select a port. And **don't** use 6667 or 6697 for it, because browsers refuse to connect to these ports.
Then, use the same port in the `-p` flag as what you chose.

What wording do you suggest?

**Comment by felixsanz** [comment]
to me it was confusing because i did not executed --makeconf yet

Maybe give information about that or use the same port in the docker readme, so at least is not that confusing

thanks!
