### ISSUE TITLE
Python.h not found

### ISSUE THREAD

**Issue by docgonzo2015** [znc/znc-docker#27]
Hi!

I'm trying to start the docker, but 'm getting a failure

`
Scanning dependencies of target module_blockuser
[ 12%] Building CXX object CMakeFiles/module_blockuser.dir/znc-data/modules/blockuser.cpp.o
[ 13%] Linking CXX shared module blockuser.so
[ 13%] Built target module_blockuser
Scanning dependencies of target module_modpython
[ 14%] Building CXX object CMakeFiles/module_modpython.dir/znc-data/modules/modpython.cpp.o
/znc-data/modules/modpython.cpp:18:10: fatal error: Python.h: No such file or directory
   18 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/module_modpython.dir/build.make:83: CMakeFiles/module_modpython.dir/znc-data/modules/modpython.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:424: CMakeFiles/module_modpython.dir/all] Error 2
make: *** [Makefile:104: all] Error 2
Traceback (most recent call last):
  File "/opt/znc/bin/znc-buildmod", line 89, in <module>
    subprocess.check_call(['cmake', '--build', '.'], cwd=build)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.

`

**Comment by DarthGandalf** [comment]
How exactly are you starting it?

**Comment by DarthGandalf** [comment]
And why did you put all these modules to /znc-data?
