### ISSUE TITLE
latest ARM is broken

### ISSUE THREAD

**Issue by Erroneuz** [znc/znc-docker#30]
Updated from 1.8.2 sha256:db254ececf401d0f7db47f515c435b080eeccf382db2085cedd9b4df8336259c to latest ARM sha256:0f911a028bb64788063a525fd640c3bb1853ffadd8f8414252a7c9a9b7c09405 on my Rapsberry PI 3b+ and determined it was broken.

Connection to ZNC works, webadmin works, but the ZNC's have issues connecting to IRC networks. Both Quakenet and Rizon didn't work, one without SSL and one with SSL. Got timeouts and even a "your client might not be compatible with Quakenet). 

Randomly did get a connection to qukanet, but couldn't perform any commands, Got a timeout soon after.

/znc listservers listed the networks, but no connection to the networks. Had a no under "Is on IRC"

Nothing to see in log,. 

Rolled back to using the older 1.8.2 image sha256:db254ececf401d0f7db47f515c435b080eeccf382db2085cedd9b4df8336259c image and it worked perfectly.

**Comment by DarthGandalf** [comment]
> Nothing to see in log,.

Anything in `znc -D`?

> your client might not be compatible with Quakenet

This is not an error from ZNC. Maybe your network had a bad connection at that time? Or Quakenet broke something?

**Comment by Erroneuz** [comment]
I rolled back, and it worked immiedietly, so don't think it was a Quakenet issue. Did also have problems with Rizon.

Gonna try to spin up a extra container tomorrow with the latest arm image, and see if I can get anything useful from znc -D
