### ISSUE TITLE
"Connection Reset" when creating a ZNC container with ssl

### ISSUE THREAD

**Issue by alecbcs** [znc/znc-docker#6]
Hi everyone, when I create a ZNC container in docker and enable SSL in the setup I am unable to connect to the ZNC container. The admin panel just says "Connection Reset". However, if I create a znc container and don't enable SSL then ZNC works flawlessly. Does anyone know how to fix this?

**Comment by DarthGandalf** [comment]
Tried https:// ?

**Comment by alecbcs** [comment]
Wow... I knew it would be something dumb like that. Thanks so much for the help!
