### ISSUE TITLE
Timezone setting not working as expected

### ISSUE THREAD

**Issue by lePoMo** [znc/znc-docker#7]
Configuring a timezone like the example "Europe/Berlin" has no effect, times will still be UTC. 

In short:
adding "`apk add --no-cache tzdata`" in the RUN section of the Dockerfile should do the trick

In longer:
The following closed issue helped me solve it: #https://github.com/znc/znc/issues/519
Alpine as configured in znc-docker behaves like described in that issue, hence concluding that timezone info is missing. After installing tzdata, running `env TZ=Europe/Berlin date` returns the expected time.

**Comment by DarthGandalf** [comment]
Thanks for the suggested fix!

**Comment by lePoMo** [comment]
thank you for having added it :)
